### ISSUE TITLE
version used for xeno is outdated

### ISSUE THREAD

**Issue by shrimp-alfredo** [ItzMaro/Xeno#10]
says you're using version 1.07 you should be using 1.08 and i legit cant find original xeno 1.08 they deleted their account of xeno and i think they cancelled

**Comment by shrimp-alfredo** [comment]
yes im using 1.09 on "zenora"

**Comment by ItzMaro** [comment]
Sry about that, I forgot to change the version from 1.0.9 to 1.0.8 I must've made it 1.0.8 at the beginning
